services:
  type: mysql:10.11
  disk: 256
  configuration:
  dbname: "%env(resolve:DATABASE_NAME)%"
  user: "%env(resolve:DATABASE_USER)%"
  password: "%env(resolve:DATABASE_PASSWORD)%"
  host: "%env(resolve:DATABASE_HOST)%"
  port: "%env(resolve:DATABASE_PORT)%"
